[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "0.22.3"
hex = "0.4.3"
itertools = "0.10.1"
ndarray = "0.15.4"
rayon = "1.5.1"
rustc-hash = "1.1.0"